apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: app-demo-pex-location
  description: Location to import all app-demo-pex catalog components
spec:
  targets:
    - ./.platform/*.yaml
